# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Set the package ecosystem to Python's pip
    directories: # Location of package manifests
      - "/test_package/nbconvert"
      - "/test_package/numpy"
      - "/test_package/pylake"
    schedule:
      interval: "daily" # How often to check for updates
    open-pull-requests-limit: 10 # Maximum number of open pull requests
    exclude-paths:
      - "env/*" # Exclude any files in the env/ directory. Those are dynamically compiled.
